# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aeda29fe1192210745caae0d763149afc45fbf66aa19ff4dfafac5c047cdf2962d14513faf725ffc017bc98e81e062267dc32698fa5e1971d4ddb24844ea2255

test:
  secret_key_base: ecc58dadfc2935f26b443a0cf91294e4748196e25a33068ac013fc5773a9f4e8354c95044d613fed8c3b860e0cfe323055504a11a4dfcf06c3499206d194ede3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
